### ISSUE TITLE
YouTube subscription counter

### ISSUE THREAD

**Issue by jakubgania** [BrianRuizy/b-r.io#60]
Hi. I noticed something. It's about the YouTube subscription counter.

This isn't really a problem but you might want to modify it.

After deploying your site's code to Vercel, not all API paths/routes works as functions. I mean the /api/youtube path has been deployed as an ISR function. Due to this, the subscription counter does't display the current number os subscriptions like, for example, the GitHub stars counter.

To change this, you can use the following code:

`export const dynamic = "force-dynamic"`

Add this line of code at the beginning of the file - /api/youtube/route.ts

I found this in the documentation below:
https://nextjs.org/docs/app/building-your-application/caching#segment-config-options
https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic

**Comment by BrianRuizy** [comment]
Thanks for this!

I'm going to be moving away from SWR fetch, to fetching on the server. But route handler will stay the same. [app/api/youtube/route.ts](https://github.com/BrianRuizy/b-r.io/blob/dc14b351aa47386114b05e58335903569dabc677/app/api/youtube/route.ts). 

Do you think I still need to make this change `export const dynamic = "force-dynamic"` in order to have the correctly updating sub count?

```tsx
import Image from "next/image";
import Link from "@/app/components/ui/Link";


// get youtube subs count from route handler api/youtube
async function getData() {
  const res = await fetch("https://b-r.io/api/youtube");
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function YouTube() {
  const data = await getData();

 ....
````
https://github.com/BrianRuizy/b-r.io/blob/dc14b351aa47386114b05e58335903569dabc677/app/components/bento/Youtube.tsx
